name: My (nix) Home-manager dotfiles

run-name: ${{ github.actor }} is testing

on:
  workflow_dispatch

jobs:
  build:
    #name: Build
    runs-on: macos-lastest
    steps:
      - name: CheckOut
        uses: actions/checkout#v3

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Turn on nix experimental feature to use nix flakes
        run: |
          [ -f "$HOME/.config/nix/nix.conf" ] || echo "experimental-features = nix-command flakes" > $HOME/.config/nix/nix.conf

      - name: build flake
        run: |
          nix build .
